#!/usr/bin/env bash
# Redirection
#!/usr/nin/env bash
# Install NGINX web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/index.nginx-debian.html
sudo service nginx start
new="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=P_SlAzsXa7E permanent;"
sudo sed -i "42i $new" /etc/nginx/sites-available/default
404="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "44i $404" /stc/nginx/sites-available/default
sudo service nginx restart
