#!/usr/bin/env bash
# Bash script to configure web-02 to be identical web-01

sudo apt-get -y update
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
sudo echo "Holberton School" > index.html
sudo mv index.html /var/www/html/
sudo echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html/ 

sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://github.com/andresgfranco permanent;' /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/a\\\terror_page 404 /404.html;" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/a\\\tadd_header X-Served-By \"\$HOSTNAME\";" /etc/nginx/sites-available/default

sudo service nginx restart
