#!/usr/bin/env bash
#Bash script that displays Holberton School 10 times, 
#but for the 9th iteration, displays Holberton School and then Hi on a new line

a=0
while [ $a -lt 10 ]
do
	echo "Holberton School"
	a=$((a + 1))
	if [ $a -eq 9 ]
	then
		echo "Hi"
	fi
done	