#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times
a="1"
while [ $a -lt 11 ]
do
    if [ $a -eq 4 ]
    then
	echo "bad luck"
    elif [ $a -eq 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    a=$((a + 1))
done
