#!/usr/bin/env bash
# Bash script that displays the number from 1 to 20 with bad lucks
c="1"
while [ $c -lt 21 ]
do
    echo $c
    case $c in
    4 ) echo "bad luck from China"
        ;;
    9 ) echo "bad luck from Japan"
      	;;
    17 ) echo "bad luck from Italy"
        ;;
    esac    
    c=$((c + 1))
done	